SCRCPY_EXTRA_ARGS="--display-id=0" \
QUEST_CAPTURE_WIDTH=1920 QUEST_CAPTURE_HEIGHT=1920 QUEST_CAPTURE_BITRATE=30000000 \
QUEST_CAPTURE_FULL_RATE=1 QUEST_CAPTURE_EYE=2 \
./scripts/quest_multi_scrcpy.sh start
